language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install --prefer-source

script:
  - ./vendor/bin/php-cs-fixer fix . --diff --dry-run
  - ./vendor/bin/phpunit

after_script:
  - ./vendor/bin/coveralls
